### ISSUE TITLE
Automatic cleanup of syscall threads

### ISSUE THREAD

**Issue by Rondom** [lkl/linux#192]
Is there a reason why syscall thread data is not automatically freed on thread exit and one has to call ´lkl_stop_syscall_thread()´ manually?
What I am proposing is to add a parameter for a cleanup-function to `lkl_ops->tls_alloc` that is passed to ´pthread_key_create´ and change `arch/lkl/kernel/syscalls.c` to make use of that. What were the design considerations behind the current design? Why does tls_alloc only have one parameter?

~~(Under Win32 there is not direct a equivalent. One can register a cleanup function, but not one per TLS variable. The quick and dirty-solution is to not care because the use in syscalls.c is the only use of `tls_alloc`, the right way would probably be to do one's own book-keeping and emulate the pthreads-behaviour. Googling points to some snippet from Chromium as an example of how to do that)~~

**Comment by Rondom** [comment]
git blame points to @tavip @opurdila, so I take the liberty to mention him ;-)

**Comment by liuyuan10** [comment]
This seems a good idea to me. It can abbreviate 64 irq limitation issue. For windows, google leads me to this thread:
http://stackoverflow.com/questions/18650956/how-to-release-the-object-in-a-tls-slot-at-thread-exit-on-windows 
I don't know about windows programming but this FlsAlloc looks promising.

**Comment by Rondom** [comment]
Thanks for the hint with FlsAlloc! The information I found was outdated, it seems (FlsAlloc was introduced with Vista). See the links below confirming that FlsAlloc can actually be used as a drop-in replacement for TlsAlloc.
http://stackoverflow.com/questions/27968850/does-winrt-really-support-thread-local-storage-functions-tls
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/043b1f9f-47f2-4905-a6ab-89c8c6172c28/thread-local-storage?forum=windowssdk

**Comment by opurdila** [comment]
FlsAlloc sounds good to me which means we can implement this in a portable way. 

The only potential issue I am think of is if there are limitation to the destructor function since lkl_stop_syscall_thread() needs to block to wait for the kernel thread to terminate.

But overall looks like a promising solution, thanks for looking into this!

**Comment by liuyuan10** [comment]
@Rondom Thanks for sharing the great idea. I actually find I also need it in my applications. Are you planning to implement it?

**Comment by Rondom** [comment]
Yes.

**Comment by Rondom** [comment]
Yes, but it might take some time until I can submit a PR.

**Comment by Rondom** [comment]
A first test with LKL-FUSE worked like a charm. I was not able to stress it enough to run out of IRQs.

**Comment by hkchu** [comment]
Will we be able to capture all the thread terminating cases here (except when it causes the whole process to die), or we can only capture the "normal exit" cases? I hope it's the former, much like the host kernel capturing all the process terminating cases so the proper cleanup can be done for all cases. Otherwise we should document what cases we can't cover so we are aware of the limitation (e.g., irq # may run out due to thread leakage...) and encourage LKL app to use the proper (e.g., pthread_exit()) terminate steps.
