### ISSUE TITLE
TCP/IP stack in LKL

### ISSUE THREAD

**Issue by speedingdaemon** [lkl/linux#377]
Hi 

Has anyone tried to use just the TCP/IP stack of LKL?
I want to see if there is a way to bypass the other LKL layers and just directly be able to pass a packet to IP layer, for example.

I am finding it a little difficult to include skbuff.h in my application and have to keep resolving build issues.

Any pointers?

Thanks!

**Comment by tavip** [comment]
Trying to use skbuff.h or TCP/IP functions directly won't work since there are a lot of dependencies you need to resolve. The only APIs LKL makes available are the system calls.

However, you can try to use the PF_PACKET (man 7 packet) or RAW (man 7 ip) socket interfaces to pass raw packets to the stack.

**Comment by speedingdaemon** [comment]
Is there a defined way to expose skbuff to an application thru LKL interface, if I need to?

**Comment by tavip** [comment]
No. skbuff APIs are a stable interface and it has too many dependencies and setup requirements to be useful for an application.

**Comment by speedingdaemon** [comment]
Thanks
