### ISSUE TITLE
Why does hijack accept non-LKL fds?

### ISSUE THREAD

**Issue by pscollins** [lkl/linux#54]
Is there a good usecase for this? It seems to me like giving a host fd to LKL is going to be programmer error 99.9% of the time, and passing it along silently to the host will generally hide the error until someone tries to mix the two together down the line. It would be nice to have an assertion fire off and fail loudly to make it clear that something has gone wrong.

Is the pass-to-host behavior needed for syscalls that touch STDOUT or something like that? If not, the hijack code could be cut simplified a lot. If it is needed for something, it would be nice at least print a warning or something.

Can this part of the library be made stricter? Or does it need to be the way it is?

**Comment by thehajime** [comment]
there are a couple of use cases.

- if an application opens a socket but also open a file (like stdin and stdout), the lib should distinguish and dispatch them
- if liblkl{.a,.so} (or linked library) uses system calls and linked with libhijack, then libhijack should treat those system calls goes to the host calls. virtio network backend (currently only with tap) required such a behavior
 - the tap case is easy to mitigate as the code is just a couple of lines, but if we depend on an external library (I'm thinking dpdk in my mind), it would be more complicated

so notifying something to callers is not always happy for users.

I would say if applications need to _only_ use LKL syscalls, the hijack library is not for them: call LKL syscall directly.

see more detail discussion in the Section "3.13.6 System Call Hijacking" of rumpkernel book (https://github.com/rumpkernel/book).

I understand handling host fds in hijack library is broken and I haven't come up with a perfect solution. and I'm so reluctant to spend more time for hijack library (because of such limitations).
but the library is only there because of the instant use case to benefit LKL with existing application binaries.

**Comment by pscollins** [comment]
Got it, very helpful explanation, thanks!
