### ISSUE TITLE
Is LKL being used somewhere for production use?

### ISSUE THREAD

**Issue by stfairy** [lkl/linux#79]
The work seems to have last for a few years.  So I wonder if there is someone already using it in some real-world products.  If there's any, we might want to create a wiki page listing them?

**Comment by tommie-lie** [comment]
Depends on how you define "productive". I am working on an emulation framework project for long-term preservation of software (for examples, see <http://eaas.uni-freiburg.de/demos.html>). For web preservation it would be nice to have old browsers (that still support blink, for instance) or to preserve a whole web application without having to crawl the passive HTML/JS code like current web archiving tools do.
To have an abstraction from the real network and also emulate stuff well out of our reach (public IP addresses), we use VDE (<http://vde.sourceforge.net/>) to connect virtual machines. This allows us to have an easy access to the network traffic and manipulate it, replacing IP addresses and port numbers.

Because we can deploy our services in the cloud and don't want to rely on root permissions or kernel features, we frown upon using tap bridges to gateway between the VDE networks and the "real" internet. I therefore used LKL and its network stack to build a SOCKS server: https://github.com/eaas-framework/lklsocks
It currently relies on an own branch of lkl which supports the VDE backend. I will send a pull request for it as soon as #67 is closed as I rely on some of its infrastructure.

The SOCKS server is not really used in a "production" scenario yet, but will be in the next couple of weeks.

We also allow to upload individual files (think upload an old Word 2.0 file you want to work on using our emulated Windoes 3.11 environment) and currently use loop mounts to pack a disk image with a FAT12 filesystem. We also plan on using lklfuse to lose another dependency for root permissions and support more filesystems (e.g. Mac's HFS) but I have not looked into that, yet.

**Comment by cee1** [comment]
Another question about "production use": under what license LKL is distributed? E.g. if an application link s against LKL, does it have to be open sourced?

**Comment by opurdila** [comment]
GPLv2 as the Linux kernel.

**Comment by cee1** [comment]
OK, that means any program link against LKL __directly__ have to be open sourced, right?

But considering Proprietary modules: how can they link the kernel, e.g. using the memcpy() symbol, without opening source code? The answer is here: http://stackoverflow.com/questions/2721290/propietary-modules-within-gpl-and-bsd-kernels

So, generally, I think LKL can be used in Proprietary products in the same way.
